# _config.yml
title: PRIMU
email: your-email@example.com
description: >-
  Project site for PRIMU.

url: "https://marcoschumacher-uniwuppertal.github.io"
baseurl: "/"


#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Admin"
  avatar: ""
  bio: ""
  location: "Wuppertal, Germany"
